# config/meta.yml

meta_product_name: "Riding Pot"
meta_title: "Riding Pot - Sorties cyclistes collaboratives
meta_description: "Relevant description"
meta_image: "cover.png" # should exist in `app/assets/images/`
twitter_account: "@product_twitter_account"   # required for Twitter Cards
